#!/bin/sh
while read -r line; do
	case $line in
		*"F1 "*) eww update ws1="$HOME/bin/dwm/bar/red.png";; 
		*"1 "*) eww update ws1="$HOME/bin/dwm/bar/white.png";; 
		*) eww update ws1="$HOME/bin/dwm/bar/black.png";;
	esac

	case $line in
		*F2*) eww update ws2="$HOME/bin/dwm/bar/red.png";;
		*2*) eww update ws2="$HOME/bin/dwm/bar/white.png";;
		*) eww update ws2="$HOME/bin/dwm/bar/black.png";;
	esac

	case $line in
		*F3*) eww update ws3="$HOME/bin/dwm/bar/red.png";;
		*3*) eww update ws3="$HOME/bin/dwm/bar/white.png";;
		*) eww update ws3="$HOME/bin/dwm/bar/black.png";;
	esac

	case $line in
		*F4*) eww update ws4="$HOME/bin/dwm/bar/red.png";;
		*4*) eww update ws4="$HOME/bin/dwm/bar/white.png";;
		*) eww update ws4="$HOME/bin/dwm/bar/black.png";;
	esac

	case $line in
		*F5*) eww update ws5="$HOME/bin/dwm/bar/red.png";;
		*5*) eww update ws5="$HOME/bin/dwm/bar/white.png";;
		*) eww update ws5="$HOME/bin/dwm/bar/black.png";;
	esac

	case $line in
		*F6*) eww update ws6="$HOME/bin/dwm/bar/red.png";;
		*6*) eww update ws6="$HOME/bin/dwm/bar/white.png";;
		*) eww update ws6="$HOME/bin/dwm/bar/black.png";;
	esac
	case $line in
		*F7*) eww update ws7="$HOME/bin/dwm/bar/red.png";;
		*7*) eww update ws7="$HOME/bin/dwm/bar/white.png";;
		*) eww update ws7="$HOME/bin/dwm/bar/black.png";;
	esac
	case $line in
		*F8*) eww update ws8="$HOME/bin/dwm/bar/red.png";;
		*8*) eww update ws8="$HOME/bin/dwm/bar/white.png";;
		*) eww update ws8="$HOME/bin/dwm/bar/black.png";;
	esac
	case $line in
		*F9*) eww update ws9="$HOME/bin/dwm/bar/red.png";;
		*9*) eww update ws9="$HOME/bin/dwm/bar/white.png";;
		*) eww update ws9="$HOME/bin/dwm/bar/black.png";;
	esac
	case $line in
		*F10*) eww update ws10="$HOME/bin/dwm/bar/red.png";;
		*10*) eww update ws10="$HOME/bin/dwm/bar/white.png";;
		*) eww update ws10="$HOME/bin/dwm/bar/black.png";;
	esac
	case $line in
		*F11*) eww update ws11="$HOME/bin/dwm/bar/red.png";;
		*11*) eww update ws11="$HOME/bin/dwm/bar/white.png";;
		*) eww update ws11="$HOME/bin/dwm/bar/black.png";;
	esac
done < <(dwm-msg --ignore-reply subscribe tag_change_event | unbuffer -p tags-calc.py)
