# https://github.com/Misterio77/flavours
#
# Example config and default values
#
# [[item]]
# file = '~/.config/example' (file to inject to, supports tilde and env var expansion. required)
# template = 'example' (template to use. required)
# subtemplate = 'default' (subtemplate to use)
# rewrite = false (should we rewrite the entire file?)
# start = '# Start flavours' (if not rewriting, where to start replacing)
# end = '# End flavours' (if not rewriting, where to stop replacing)
# hook = '' (command to execute after injecting)
#
# Example for i3
#
# [[item]]
# file = '~/.config/i3/config'
# template = 'i3'
# subtemplate = 'colors'
# hook = 'i3-msg reload'
# rewrite = false
[[item]]
file = '~/otr/git/lesssuck/st/flavours_diff'
template = 'st'
hook = 'st_flavours_compile'
rewrite = true

[[item]]
file = '~/.config/dunst/dunstrc'
template = 'dunst'
rewrite = false
hook = 'dunst_run'
start = '# Start flavours'
end = '# End flavours'

[[item]]
file = '~/bin/bar/colors'
template = 'status'
rewrite = true

[[item]]
file = '~/.config/rofi/config.rasi'
template = 'rofi'
rewrite = true

[[item]]
file = '~/.config/foot/foot.ini'
template = 'foot'
rewrite = false
start = '# Start flavours'
end = '# End flavours'

[[item]]
file = '~/.config/eww/eww.scss'
template = 'eww'
rewrite = false
start = '// Start flavours'
end = '// End flavours'

[[item]]
file = '~/.config/xob/styles.cfg'
template = 'xob'
hook = 'xobvolume_run'
rewrite = false
start = '# Start flavours'
end = '# End flavours'

