#!/bin/bash
while read -r line; do
    case "$line" in
	    "Event 'change' on sink"*)
		    eww update volume="$(pulsemixer --get-volume | cut -f2 -d' ')"
		    eww open volume_panel;;
	    *);;
    esac
done < <(pactl subscribe)
